language: go
sudo: false

env:
  global:
  - ESCHER=src

matrix:
  include:
    - go: 1.12.x
      os: linux
      env: ONCE=true
    - go: 1.11.x
      os: osx
    - name: Cross-Compile for windows (from Linux)
      go: 1.11.x
      os: linux
      env: GOOS=windows GOARCH=amd64 CGO_ENABLED=0

# Allow use in forks
go_import_path: github.com/gocircuit/escher

install:
- go get -v github.com/gocircuit/circuit/client
- go get -v github.com/gocircuit/circuit/client/docker
- go get -v -t ./...

script:
- make
- escher "*test.All"
- if [ "$ONCE" = "true" ]; then scripts/build_handbook.sh; fi
- if [ "$ONCE" = "true" ]; then scripts/runTutorials.sh; fi
