<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>escher</string>
	</array>
	<key>name</key>
	<string>Escher</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>comment.line.double-slash.escher</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.escher</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.escher</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.escher</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.escher</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.escher</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.raw.escher</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.gotemplate</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\d+\.(\d+)?([eE][+-]?\d+)?|\d+[eE][+-]?\d+|\.\d+([eE][+-]?\d+)?)i?)\b</string>
			<key>name</key>
			<string>constant.numeric.floating-point.escher</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+i|0[xX][0-9A-Fa-f]+|0[0-7]*|[1-9][0-9]*)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.escher</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(?:[^'\\]|\\(?:\\|[abfnrtv']|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|U[0-9a-fA-F]{8}|[0-7]{3}))'</string>
			<key>name</key>
			<string>constant.other.rune.escher</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.escher</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.initialize.escher</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This matches the 'x := 0' style of variable declaration.</string>
			<key>match</key>
			<string>(?:[[:alpha:]_][[:alnum:]_]*)(?:,\s+[[:alpha:]_][[:alnum:]_]*)*\s*(=)</string>
			<key>name</key>
			<string>meta.initialization.short.escher</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|(?:[+]|-|[|]|^|[*]|/|%|&lt;&lt;|&gt;&gt;|&amp;|&amp;^)=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.escher</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;)</string>
			<key>name</key>
			<string>keyword.operator.semi-colon.escher</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,)</string>
			<key>name</key>
			<string>punctuation.definition.comma.escher</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.escher</string>
	<key>uuid</key>
	<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
